# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public

only:
  - main