image: node:lts

before_script:
  - npm ci

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r public/* public/
  artifacts:
    paths:
      - public
  only:
    - main