image: node:latest

pages:
  # Only need deploy stage
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - cd Webpage
    - npm install
    - npm run build
  artifacts:
    paths:
      - Webpage/build
  publish: Webpage/build
  only:
    - main